
project_id = "fsogbfwwznjrqpalyhhf"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[[hooks.deploy]]
id = "sync-types"
command = "npx supabase gen types typescript --local > src/integrations/supabase/types.ts"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
autoconfirm = true
disable_signup = false

[functions.seed-demo-data]
verify_jwt = false
