// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsogbfwwznjrqpalyhhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzb2diZnd3em5qcnFwYWx5aGhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNTkwMzUsImV4cCI6MjA2MTczNTAzNX0.15Z-_4zKzn4AOcpqWWn-mESo9O20lVP1PnsWu8cULjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);